import React from "react";

const activities = [
    {
        id: 1,
        activityName: "Basketball",
        club: "CMBC Friday Night Hoops 2024",
        category: "Scrimmage",
        mapIcon: "basketball.png",
        latitude: "51.50419287852187",
        longitude: "-2.547285967955848",
        venue: "UWE Center for Sport",
        googleMapURL: "https://maps.app.goo.gl/o4VRSEDVHT1PgFeo8",
        description: "We arranged this run to give players preparing for senior national league or above next season a chance to keep working at a high level with promotional support and coaching input from CMBC. We open for players who have purchased a block booking to claim a spot for the following Friday immediately after the session finishes at 21:30. We cap the run at 16 players per court and have a reserve list after that. To claim a space just put your name and the spot you are claiming in the WhatsApp chat after bookings are open to you e.g. 1 Ben.",
        whatsappURL: "",
        webURL: "",
        instagramURL: "",
        facebookURL: "",
        xURL: "",
        youtubeURL: "",
        lead: "Owen Parker",
        cost: "Cost is £10 each per session or £9 per session for a block of sessions e.g. £90 for 10 sessions. Blocks are sold on an invite only basis.",
        shortCost: "£10/session",
        payment: {
          name: "Ball Park Events",
          bank: "Lloyds Bank",
          accountNumber: "58922262",
          sortCode: "30-98-97"
        },
        time: "Friday 20:00-21:30",
        shortTime: "Friday (8-9.30pm)",
        image:"https://media-lhr8-1.cdn.whatsapp.net/v/t61.24694-24/420532011_3315151045445411_4252655712371525139_n.jpg?ccb=11-4&oh=01_Q5AaIBjJiOqD2EKusYzxXQEzYdnEPivCmIZ7PebXItotgVoP&oe=66630F7C&_nc_sid=e6ed6c&_nc_cat=102"
    },
    {
        id: 2,
        activityName: "Basketball",
        club: "Bristol Uni Summer Runs 2024",
        category: "Scrimmage",
        mapIcon: "basketball.png",
        latitude: "51.45922782344154",
        longitude: "-2.602599061358881",
        venue: "University of Bristol Indoor Sports Centre",
        googleMapURL: "https://maps.app.goo.gl/tnrTAGaEsrz6oM2RA",
        description: "For Webba level players and above. Max 16-20 players. Format half court 4 v 4.",
        whatsappURL: "https://chat.whatsapp.com/KlxqGJcvxgP0Ig4vchPXZQ",
        webURL: "",
        instagramURL: "",
        facebookURL: "",
        xURL: "",
        youtubeURL: "",
        lead: "Hans Johnson",
        cost: "£2.70 to £4 depending on numbers",
        shortCost: "£2.70-£4/session",
        payment: {
          name: "Hans Johnson",
          bank: "Lloyds Bank",
          accountNumber: "34658560",
          sortCode: "30-18-88"
        },
        time: "June to September. Friday 6-8pm (sign up from Sunday 9pm). Sunday 4-6pm (sign up from Thursday 8pm)",
        shortTime: "Friday (6-8pm) & Sunday (4-6pm)",
        image: "https://www.bristolflyers.co.uk/wp-content/uploads/2019/07/panos4.jpeg"            
    },
    {
        id: 3,
        activityName: "Basketball",
        club: "Bristol Bandits",
        category: "Summer League",
        mapIcon: "basketball.png",
        latitude: "51.50419287852187",
        longitude: "-2.547285967955848",
        venue: "UWE Center for Sport",
        googleMapURL: "https://maps.app.goo.gl/o4VRSEDVHT1PgFeo8",
        description: "2024 Summer league basketball Bristol Bandits",
        whatsappURL: "",
        webURL: "",
        instagramURL: "",
        facebookURL: "",
        xURL: "",
        youtubeURL: "",
        lead: "Hans Johnson",
        cost: "£33.33 for the whole season",
        shortCost: "£33",
        payment: {
            name: "Hans Johnson",
            bank: "Lloyds Bank",
            accountNumber: "34658560",
            sortCode: "30-18-88"
          },
        time: "Tuesday/Wednesday from 25th June to 24th July 2024  at 18:30 - 22:00pm",
        shortTime: "Tuesday/Wednesday (6.30-10pm)",
        image:"https://www.upandundersports.co.uk/wp-content/uploads/2019/06/Daniel-1.jpg"   
    },
    {
      id: 4,
      activityName: "Football",
      club: "E5 Lions",
      category: "Club",
      mapIcon: "soccer-field.png",
      latitude: "51.46500057431809",
      longitude: "-2.6252139012856146",
      venue: "Clifton Down",
      googleMapURL: "https://maps.app.goo.gl/JA9gRrPmjDiSMZpz6",
      description: "Church League football team. Join now!",
      whatsappURL: "",
      webURL: "",
      instagramURL: "",
      facebookURL: "",
      xURL: "",
      youtubeURL: "",
      lead: "Julian King",
      cost: "£5 per game and £3 per training",
      shortCost: "£5 per game and £3 per training",
      payment: {
          name: "Julian King",
          bank: "Lloyds Bank",
          accountNumber: "34658560",
          sortCode: "30-18-88"
        },
      time: "Training on Mondays 7pm-9pm and Games on Saturdays 9am-12pm",
      shortTime: "Training - Monday (7-9pm) Games - Saturday (9am-12pm)",
      image:"https://cdn.britannica.com/51/190751-131-B431C216/soccer-ball-goal.jpg"   
  },
  {
    id: 5,
    activityName: "Badminton",
    club: "Everyone Active",
    category: "Social",
    mapIcon: "badminton.png",
    latitude: "51.459748975262826",
    longitude: "-2.573864326903628",
    venue: "Easton Leisure Centre",
    googleMapURL: "https://maps.app.goo.gl/ehaDETtNRhF492D2A",
    description: "Cheeky sesh of Badminton with pals!",
    whatsappURL: "",
    webURL: "https://www.everyoneactive.com/centre/easton-leisure-centre/",
    instagramURL: "",
    facebookURL: "",
    xURL: "",
    youtubeURL: "",
    lead: "Everyone Active",
    cost: "£11.50/hour",
    shortCost: "£11.50/hour",
    payment: {
        name: "Julian King",
        bank: "Lloyds Bank",
        accountNumber: "34658560",
        sortCode: "30-18-88"
      },
    time: "Book online",
    shortTime: "Book online",
    image:"https://www.racquetpoint.com/cdn/shop/articles/what-is-badminton-racquet-point.jpg?v=1654120169"   
},

];

export default activities;